spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/afterglow
    username: ${DB_USERNAME:afterglow}
    password: ${DB_PASSWORD:afterglow}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    com.afterglow: debug
