CREATE TABLE story_like (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    account_id BIGINT NOT NULL,
    story_id   BIGINT NOT NULL,
    CONSTRAINT uq_story_like_account_story UNIQUE (account_id, story_id),
    CONSTRAINT fk_story_like_story
        FOREIGN KEY (story_id) REFERENCES story (id)
);
