CREATE TABLE story_comment (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    story_id   BIGINT NOT NULL,
    account_id BIGINT NOT NULL,
    content    TEXT NOT NULL,
    CONSTRAINT fk_story_comment_story
        FOREIGN KEY (story_id) REFERENCES story (id)
);
