-- Flyway baseline: Flyway 도입 시점(2026-08-14)까지 Hibernate ddl-auto=update가 만들어온
-- 실제 운영/로컬 스키마를 그대로 재현한다. 이 파일은 "현재 상태의 snapshot"이며, 스키마 개선이나
-- 무결성 강화를 위한 변경은 포함하지 않는다(예: @ElementCollection 테이블에 PK/unique 없음, 이것도
-- 현재 실제 상태 그대로 유지). 컬럼 타입/길이/nullable/제약 이름은 로컬 PostgreSQL을 직접 조회해
-- 확인한 값과 동일하다. Onboarding 스키마는 아직 구현 전이라 포함하지 않는다(추후 V2).

-- ============================================================
-- account
-- ============================================================
CREATE TABLE account (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP(6),
    updated_at         TIMESTAMP(6),
    email              VARCHAR(255),
    email_verified_at  TIMESTAMP(6),
    CONSTRAINT ukq0uja26qgu1atulenwup9rxyr UNIQUE (email)
);

-- ============================================================
-- email_verification
-- ============================================================
CREATE TABLE email_verification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    code         VARCHAR(255) NOT NULL,
    consumed_at  TIMESTAMP(6),
    email        VARCHAR(255) NOT NULL,
    expires_at   TIMESTAMP(6) NOT NULL,
    purpose      VARCHAR(255) NOT NULL,
    CONSTRAINT email_verification_purpose_check
        CHECK (purpose IN ('SIGNUP', 'LOGIN'))
);

-- ============================================================
-- episode
-- ============================================================
CREATE TABLE episode (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at               TIMESTAMP(6),
    updated_at               TIMESTAMP(6),
    account_id               BIGINT NOT NULL,
    notes                    VARCHAR(255),
    onset_period             VARCHAR(255),
    recent_new_product_name  VARCHAR(255),
    status                   VARCHAR(255) NOT NULL,
    symptom_angle            DOUBLE PRECISION NOT NULL,
    primary_symptom          VARCHAR(255) NOT NULL,
    symptom_radius           DOUBLE PRECISION NOT NULL,
    severity                 VARCHAR(255) NOT NULL,
    CONSTRAINT episode_onset_period_check
        CHECK (onset_period IN ('TODAY', 'TWO_TO_THREE_DAYS_AGO', 'ONE_WEEK_AGO', 'TWO_WEEKS_OR_MORE')),
    CONSTRAINT episode_status_check
        CHECK (status IN ('SYMPTOM_SELECTED', 'INTAKE_COMPLETED')),
    CONSTRAINT episode_primary_symptom_check
        CHECK (primary_symptom IN ('DRYNESS_TIGHTNESS', 'ITCHING', 'STINGING', 'REDNESS', 'TROUBLE')),
    CONSTRAINT episode_severity_check
        CHECK (severity IN ('NORMAL', 'MILD', 'MODERATE', 'SEVERE'))
);

-- @ElementCollection(Set<BodyPart>) — 현재 DB-level PK/unique 없음(그대로 재현, 강화하지 않음)
CREATE TABLE episode_body_part (
    episode_id  BIGINT NOT NULL,
    body_part   VARCHAR(255),
    CONSTRAINT episode_body_part_body_part_check
        CHECK (body_part IN ('FOREHEAD', 'EYE_AREA', 'CHEEK', 'AROUND_MOUTH', 'CHIN', 'WHOLE_FACE')),
    CONSTRAINT fkeol1qf48gfhmpfxd30albhbi4
        FOREIGN KEY (episode_id) REFERENCES episode (id)
);

-- ============================================================
-- product (vanity 도메인 — 담당은 다른 팀원이지만 이미 @Entity로 persistence model에 포함되어 있어
-- fresh DB에서 Hibernate validate가 통과하려면 반드시 필요. Entity 자체는 수정하지 않는다.)
-- ============================================================
CREATE TABLE product (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at            TIMESTAMP(6),
    updated_at            TIMESTAMP(6),
    account_id            BIGINT NOT NULL,
    barcode               VARCHAR(255),
    brand                 VARCHAR(255),
    key_ingredients       VARCHAR(255),
    name                  VARCHAR(255) NOT NULL,
    opened_at             DATE,
    photo_key             VARCHAR(255),
    registration_source   VARCHAR(255) NOT NULL,
    type                  VARCHAR(255),
    usage_timing          VARCHAR(255),
    CONSTRAINT product_registration_source_check
        CHECK (registration_source IN ('BARCODE', 'PHOTO', 'MANUAL')),
    CONSTRAINT product_usage_timing_check
        CHECK (usage_timing IN ('MORNING', 'EVENING', 'BOTH'))
);

-- @ElementCollection(Set<String> functionTags) — 자유 텍스트, check 없음(현재 상태 그대로)
CREATE TABLE product_function_tag (
    product_id  BIGINT NOT NULL,
    tag         VARCHAR(255),
    CONSTRAINT fkciuf738p6snkrw6rugarymt81
        FOREIGN KEY (product_id) REFERENCES product (id)
);

-- @ElementCollection(Set<InteractionTag> interactionTags)
CREATE TABLE product_interaction_tag (
    product_id  BIGINT NOT NULL,
    tag         VARCHAR(255),
    CONSTRAINT product_interaction_tag_tag_check
        CHECK (tag IN ('RETINOL', 'ACID', 'VITAMIN_C', 'HIGH_CONCENTRATION', 'LOW_IRRITATION')),
    CONSTRAINT fk54w23nph4leffbqnwm70r4mmt
        FOREIGN KEY (product_id) REFERENCES product (id)
);

-- ============================================================
-- combination_rule (vanity 도메인, 위와 동일한 이유로 포함)
-- ============================================================
CREATE TABLE combination_rule (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at       TIMESTAMP(6),
    updated_at       TIMESTAMP(6),
    min_count        INTEGER NOT NULL,
    taga             VARCHAR(255) NOT NULL,
    tagb             VARCHAR(255),
    warning_message  VARCHAR(255) NOT NULL,
    CONSTRAINT combination_rule_taga_check
        CHECK (taga IN ('RETINOL', 'ACID', 'VITAMIN_C', 'HIGH_CONCENTRATION', 'LOW_IRRITATION')),
    CONSTRAINT combination_rule_tagb_check
        CHECK (tagb IN ('RETINOL', 'ACID', 'VITAMIN_C', 'HIGH_CONCENTRATION', 'LOW_IRRITATION'))
);
