-- 온보딩(연령대/월경 상태) 테이블 신설. V1__baseline.sql은 수정하지 않는다.
-- account와는 다른 도메인의 accountId 참조 관례대로 FK 없이 account_id 컬럼만 둔다.

CREATE TABLE onboarding (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                TIMESTAMP(6),
    updated_at                TIMESTAMP(6),
    account_id                BIGINT NOT NULL,
    age_range                 VARCHAR(255),
    menstrual_status          VARCHAR(255),
    onboarding_completed_at   TIMESTAMP(6),
    CONSTRAINT uk_onboarding_account_id UNIQUE (account_id),
    CONSTRAINT onboarding_age_range_check
        CHECK (age_range IN ('FORTY_TO_FORTY_FOUR', 'FORTY_FIVE_TO_FORTY_NINE', 'FIFTY_TO_FIFTY_FOUR', 'FIFTY_FIVE_TO_FIFTY_NINE', 'SIXTY_OR_OLDER')),
    CONSTRAINT onboarding_menstrual_status_check
        CHECK (menstrual_status IN ('REGULAR', 'IRREGULAR', 'SKIPPED_TWO_MONTHS_OR_MORE', 'MENOPAUSE_ONE_YEAR_OR_MORE', 'ABSENT_DUE_TO_SURGERY_OR_TREATMENT', 'PREFER_NOT_TO_ANSWER'))
);
