-- 일일 1탭 체크(4.1) 기록 테이블 신설. V1/V2는 수정하지 않는다.
-- Episode 하위 서브도메인 고유 데이터라 episode_id 값 참조만 쓴다(FK 없음, 다른 도메인과 동일한 관례).

CREATE TABLE check_in (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    episode_id      BIGINT NOT NULL,
    check_in_date   DATE NOT NULL,
    status          VARCHAR(255) NOT NULL,
    CONSTRAINT uk_check_in_episode_date UNIQUE (episode_id, check_in_date),
    CONSTRAINT check_in_status_check
        CHECK (status IN ('IMPROVED', 'SAME', 'WORSE'))
);
