-- 3일 루틴(3.2, Manyfast F-VUQBTM) 테이블 신설. V1~V3은 수정하지 않는다.
-- Episode 하위 서브도메인 고유 데이터라 episode_id/account_id 값 참조만 쓴다(FK 없음, check_in과 동일한 관례).
-- Episode당 Routine은 하나만 존재한다(EpisodeAnalysisResult와 동일한 설계 원칙 — episode_id unique).

CREATE TABLE routine (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),
    episode_id  BIGINT NOT NULL,
    account_id  BIGINT NOT NULL,
    start_date  DATE NOT NULL,
    status      VARCHAR(255) NOT NULL,
    CONSTRAINT uk_routine_episode UNIQUE (episode_id),
    CONSTRAINT routine_status_check
        CHECK (status IN ('ACTIVE'))
);

-- @ElementCollection(List<RoutineItem>) + @OrderColumn(item_order) — 제품 순서 보존.
-- CONTINUE는 day_number/time_slot이 필수, DISCONTINUE(3일 전체 적용)는 둘 다 NULL이다.
CREATE TABLE routine_item (
    routine_id  BIGINT NOT NULL,
    item_order  INTEGER NOT NULL,
    usage_type  VARCHAR(255) NOT NULL,
    day_number  INTEGER,
    time_slot   VARCHAR(255),
    product_id  BIGINT NOT NULL,
    PRIMARY KEY (routine_id, item_order),
    CONSTRAINT fk_routine_item_routine
        FOREIGN KEY (routine_id) REFERENCES routine (id),
    CONSTRAINT routine_item_usage_type_check
        CHECK (usage_type IN ('CONTINUE', 'DISCONTINUE')),
    CONSTRAINT routine_item_time_slot_check
        CHECK (time_slot IN ('MORNING', 'EVENING') OR time_slot IS NULL)
);
