CREATE TABLE daily_tracking (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    account_id        BIGINT NOT NULL,
    recorded_date     DATE NOT NULL,
    sleep_level       VARCHAR(255) NOT NULL,
    condition_level   VARCHAR(255) NOT NULL,
    temperature       DOUBLE PRECISION,
    humidity          DOUBLE PRECISION,
    uv_index          DOUBLE PRECISION,
    CONSTRAINT uk_daily_tracking_account_date
        UNIQUE (account_id, recorded_date),
    CONSTRAINT daily_tracking_sleep_level_check
        CHECK (sleep_level IN ('WELL', 'NORMAL', 'POOR')),
    CONSTRAINT daily_tracking_condition_level_check
        CHECK (condition_level IN ('GOOD', 'NORMAL', 'BAD'))
);
