CREATE TABLE story (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    account_id        BIGINT NOT NULL,
    title             VARCHAR(255) NOT NULL,
    content           TEXT NOT NULL,
    life_stage        VARCHAR(255),
    life_stage_public BOOLEAN NOT NULL,
    like_count        INTEGER NOT NULL,
    hidden            BOOLEAN NOT NULL,
    CONSTRAINT story_life_stage_check
        CHECK (life_stage IN ('PERIMENOPAUSE', 'MENOPAUSE', 'POST_MENOPAUSE'))
);

CREATE TABLE story_symptom_tag (
    story_id      BIGINT NOT NULL,
    symptom_tag   VARCHAR(255),
    CONSTRAINT story_symptom_tag_check
        CHECK (symptom_tag IN (
            'DRYNESS_TIGHTNESS',
            'ITCHING',
            'STINGING',
            'REDNESS',
            'TROUBLE'
        )),
    CONSTRAINT fk_story_symptom_tag_story
        FOREIGN KEY (story_id) REFERENCES story (id)
);

CREATE TABLE story_situation_tag (
    story_id       BIGINT NOT NULL,
    situation_tag  VARCHAR(255),
    CONSTRAINT story_situation_tag_check
        CHECK (situation_tag IN (
            'SLEEP_DEPRIVATION',
            'STRESS',
            'SEASON_WEATHER',
            'ALCOHOL',
            'SPICY_FOOD_COFFEE',
            'MENSTRUAL_CYCLE'
        )),
    CONSTRAINT fk_story_situation_tag_story
        FOREIGN KEY (story_id) REFERENCES story (id)
);
