CREATE TABLE notification_setting (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at         TIMESTAMP(6),
    updated_at         TIMESTAMP(6),
    account_id         BIGINT NOT NULL,
    type               VARCHAR(255) NOT NULL,
    enabled            BOOLEAN NOT NULL,
    notification_time  TIME NOT NULL,
    timezone           VARCHAR(255) NOT NULL,
    CONSTRAINT notification_setting_type_check
        CHECK (type IN ('ROUTINE', 'DAILY_TRACKING'))
);
